### ISSUE TITLE
How to install remote version?

### ISSUE THREAD

**Issue by LinkunGao** [tgbugs/ontquery#33]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/80797317/183345090-c09b9757-fe09-469f-852a-699fcabb5b97.png">

Is this need a specific python version?

**Comment by tgbugs** [comment]
The issue is that zsh doesn't like the square brackets so they have to go in quotes.

`python3 -m pip install "ontquery[services]"` should work in zsh and I updated the readme to avoid that pitfall. Thanks for the report.
